# docker-compose.yml -> docker compose up
version: '3.3'
services:
  database:
    image: postgres:12.1-alpine
    restart: always
    container_name: node-api-base
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_database
    ports:
      - '5433:5432'
    volumes:
      - ./tmp/data/db:/var/lib/postgresql/data
  database_test:
    image: postgres:12.1-alpine
    container_name: node-api-base-test
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app_database_test
    ports:
      - '5434:5432'